version: "2"
services:
  db:
    image: chuymedina96/utopia_flask_mysql:v1.0
    restart: always
    ports:
      - ${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}

  bookings:  
    image: chuymedina96/utopia_flask_bookings:v1.0
    depends_on:
      - db
    links:
      - db
    ports:
        - ${BOOKINGS_PORTS}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}

  flights: 
    image: chuymedina96/utopia_flask_flights:v1.0
    depends_on:
      - db
    links:
      - db
    ports:
        - ${FLIGHTS_PORTS}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}
  users: 
    image: chuymedina96/utopia_flask_users:v1.0
    depends_on:
      - db
    links:
      - db
    ports:
        - ${USERS_PORTS}
    
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}


